/**
 * Centralized inline styles for the app chrome (sidebar + tab bar).
 * Excalidraw's own UI styling comes from its SCSS via the source alias.
 */

export const COLORS = {
  sidebarBg: "#f8f9fa",
  sidebarBorder: "#e9ecef",
  itemHover: "#e9ecef",
  itemOpen: "#d0ebff",
  text: "#343a40",
  textMuted: "#868e96",
  accent: "#4d96ff",
  danger: "#fa5252",
  star: "#fab005",
};

export const sidebarStyle = {
  container: {
    width: "260px",
    minWidth: "260px",
    height: "100%",
    backgroundColor: COLORS.sidebarBg,
    borderRight: `1px solid ${COLORS.sidebarBorder}`,
    display: "flex" as const,
    flexDirection: "column" as const,
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: "13px",
  },
  viewSwitch: {
    display: "flex" as const,
    gap: "4px",
    padding: "8px 8px 0 8px",
  },
  viewBtn: {
    flex: 1,
    padding: "5px 0",
    border: `1px solid ${COLORS.sidebarBorder}`,
    borderRadius: "6px",
    cursor: "pointer" as const,
    fontSize: "12px",
    backgroundColor: "#fff",
    color: COLORS.textMuted,
  },
  viewBtnActive: {
    backgroundColor: COLORS.accent,
    color: "#fff",
    borderColor: COLORS.accent,
    fontWeight: 600 as const,
  },
  folderBar: {
    padding: "6px 10px",
    borderBottom: `1px solid ${COLORS.sidebarBorder}`,
  },
  folderBtn: {
    width: "100%",
    padding: "6px",
    border: `1px solid ${COLORS.sidebarBorder}`,
    borderRadius: "6px",
    cursor: "pointer" as const,
    fontSize: "12px",
    backgroundColor: "#fff",
  },
  folderPath: {
    marginTop: "4px",
    fontSize: "11px",
    color: COLORS.textMuted,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  errorMsg: {
    padding: "6px 12px",
    color: COLORS.danger,
    fontSize: "12px",
  },
  header: {
    display: "flex" as const,
    gap: "6px",
    padding: "10px",
    borderBottom: `1px solid ${COLORS.sidebarBorder}`,
  },
  search: {
    flex: 1,
    padding: "6px 10px",
    border: `1px solid ${COLORS.sidebarBorder}`,
    borderRadius: "6px",
    fontSize: "13px",
    outline: "none",
    backgroundColor: "#fff",
  },
  iconBtn: {
    width: "32px",
    height: "32px",
    border: `1px solid ${COLORS.sidebarBorder}`,
    borderRadius: "6px",
    cursor: "pointer" as const,
    fontSize: "16px",
    lineHeight: "1",
    padding: "0",
  },
  newBtn: {
    width: "32px",
    height: "32px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer" as const,
    fontSize: "20px",
    lineHeight: "1",
    padding: "0",
    backgroundColor: COLORS.accent,
    color: "#fff",
    fontWeight: 600 as const,
  },
  list: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "6px",
  },
  empty: {
    padding: "24px 12px",
    color: COLORS.textMuted,
    textAlign: "center" as const,
    fontSize: "12px",
  },
  item: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "6px",
    borderRadius: "6px",
    cursor: "pointer" as const,
    marginBottom: "2px",
  },
  itemOpen: {
    backgroundColor: COLORS.itemOpen,
  },
  thumb: {
    width: "40px",
    height: "30px",
    border: `1px solid ${COLORS.sidebarBorder}`,
    borderRadius: "4px",
    overflow: "hidden" as const,
    flexShrink: 0,
    backgroundColor: "#fff",
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  thumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
  },
  thumbPlaceholder: {
    color: COLORS.textMuted,
    fontSize: "16px",
  },
  itemMeta: {
    flex: 1,
    minWidth: 0,
  },
  itemName: {
    color: COLORS.text,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    fontSize: "13px",
  },
  itemTime: {
    color: COLORS.textMuted,
    fontSize: "11px",
    marginTop: "2px",
  },
  itemActions: {
    display: "flex" as const,
    gap: "2px",
    opacity: 0.5,
  },
  starBtn: {
    border: "none",
    background: "transparent",
    cursor: "pointer" as const,
    fontSize: "14px",
    padding: "2px 4px",
    color: COLORS.star,
  },
  delBtn: {
    border: "none",
    background: "transparent",
    cursor: "pointer" as const,
    fontSize: "16px",
    padding: "2px 4px",
    color: COLORS.danger,
    lineHeight: "1",
  },
};

export const tabBarStyle = {
  container: {
    display: "flex" as const,
    alignItems: "flex-end" as const,
    backgroundColor: COLORS.sidebarBg,
    borderBottom: `1px solid ${COLORS.sidebarBorder}`,
    padding: "0 8px",
    height: "38px",
    fontFamily: "system-ui, -apple-system, sans-serif",
    flexShrink: 0,
    overflowX: "auto" as const,
  },
  tab: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    padding: "6px 12px",
    cursor: "pointer" as const,
    fontSize: "13px",
    color: COLORS.textMuted,
    border: "1px solid transparent",
    borderBottom: "none",
    borderRadius: "6px 6px 0 0",
    maxWidth: "200px",
    whiteSpace: "nowrap" as const,
  },
  tabActive: {
    backgroundColor: "#fff",
    borderColor: COLORS.sidebarBorder,
    color: COLORS.text,
  },
  tabName: {
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  dirtyDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: COLORS.accent,
    flexShrink: 0,
  },
  closeBtn: {
    border: "none",
    background: "transparent",
    cursor: "pointer" as const,
    fontSize: "15px",
    lineHeight: "1",
    padding: "0 2px",
    color: COLORS.textMuted,
    borderRadius: "3px",
  },
  newTabBtn: {
    border: "none",
    background: "transparent",
    cursor: "pointer" as const,
    fontSize: "18px",
    padding: "4px 10px",
    color: COLORS.textMuted,
    lineHeight: "1",
  },
};

export const appLayoutStyle = {
  root: {
    display: "flex" as const,
    height: "100%",
    width: "100%",
  },
  main: {
    flex: 1,
    display: "flex" as const,
    flexDirection: "column" as const,
    minWidth: 0,
  },
  editorArea: {
    flex: 1,
    position: "relative" as const,
    minHeight: 0,
  },
};
